# Generated by Selenium IDE
import pytest
import time
import json
from needle.cases import NeedleTestCase
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class MyTests(NeedleTestCase):

    @classmethod
    def get_web_driver(cls):
        return NeedleChrome()
n=MyTests()        
n.driver.get("http://localhost:94/")
n.driver.set_window_size(1054, 900)

